### ISSUE TITLE
Could not resolve dependencies

### ISSUE THREAD

**Issue by developerworks** [Jotschi/vertx-graphql-example#1]
```
[ERROR] Failed to execute goal on project vertx-graphql-example: Could not resolve dependencies 
for project de.jotschi:vertx-graphql-example:jar:0.0.1-SNAPSHOT: 
Failure to find com.gentics.ferma:ferma-extensions-orientdb-vertx:jar:0.0.5-SNAPSHOT 
in https://maven.gentics.com/maven2 was cached in the local repository, resolution will 
not be reattempted until the update interval of maven.gentics.com has elapsed or updates 
are forced -> [Help 1]

```

**Comment by developerworks** [comment]
There is no `ferma-extensions-orientdb-vertx` lib in https://maven.gentics.com/maven2/com/gentics/ferma/

**Comment by Jotschi** [comment]
@developerworks - I'm waiting for https://github.com/Syncleus/Ferma-OrientDB to release the extension. Once that has been done the example should only contain dependencies to maven central.

**Comment by Jotschi** [comment]
I have now updated the dependencies. Please take a look in the master branch. That version will also utilize the tinkerpop 3.x API.
